workflows:
  ios_publish_only:
    name: "iOS Publish Only"
    environment:
      groups:
        - app_store_credentials     # ← você cria esse grupo no painel
    scripts:
      - name: Prepare artifacts
        script: |
          echo "Preparing artifacts folder..."
          mkdir -p artifacts
          # Coloque seu .ipa em ./artifacts antes de iniciar a build
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY   # carregado do grupo
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        ipa_path: "artifacts/*.ipa"
        submit_to_testflight: true
        submit_to_app_store: false
