workflows:
  ios_publish_only:
    name: "iOS Publish Only"
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Envie_pelo_Dashboard
        APP_STORE_CONNECT_KEY_IDENTIFIER: Envie_pelo_Dashboard
      secure:
        APP_STORE_CONNECT_PRIVATE_KEY: Envie_pelo_Dashboard
    scripts:
      - name: Prepare artifacts directory
        script: |
          echo "🔧 Preparing artifacts…"
          mkdir -p artifacts
          # Se estiver enviando via upload manual, não precisa copiar nada aqui.
          # Apenas garanta que seu .ipa esteja em ./artifacts antes de publicar.
    publishing:
      app_store_connect:
        apple_id: "seu-email-apple@icloud.com"
        ipa_path: "artifacts/*.ipa"
        submit_to_app_store: false            # Enviar automaticamente para revisão? (opcional)
        submit_to_testflight: true            # Publicar no TestFlight
