workflows:
  ios_publish_only:
    name: "iOS Publish Only"
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials     # Grupo criado no painel
    scripts:
      - name: Preparar pasta
        script: |
          mkdir -p artifacts
          echo "Coloque seu IPA manualmente em artifacts/"
    artifacts:
      - artifacts/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        ipa_path: "artifacts/*.ipa"
        submit_to_testflight: true
        submit_to_app_store: false
