workflows:
  ios_publish_only:
    name: "iOS Publish Only"
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials   # coloque suas credenciais de API do App Store Connect aqui
    scripts:
      - name: Instalar Fastlane
        script: |
          gem install fastlane

      - name: Fazer upload do IPA
        script: |
          echo "Iniciando upload para App Store Connect..."
          fastlane deliver \
            --api_key_path ./auth/key.json \
            --ipa ./artifacts/app.ipa \
            --skip_screenshots \
            --skip_metadata \
            --skip_app_version_update
    artifacts:
      - artifacts/*.ipa
